import { INfse, NewNfse } from './nfse.model';

export const sampleWithRequiredData: INfse = {
  id: 28116,
};

export const sampleWithPartialData: INfse = {
  id: 78442,
  ip: 'neural',
  statusNfse: 'esmeralda compress',
  statusAceite: 72305,
  ajustada: 'copy',
  observacaoAjuste: 'Hong AGP Gourde',
  aliquotaServico: 'open-source',
  codigoObra: 'Administrator cinza',
  valorPis: 'haptic',
  valorLiquidoNfse: 'Seicheles',
  valorInss: 'bypass Algodão mindshare',
  valorDeducoes: 'Lustroso Esportes vermelho',
  issRetido: 'digital Alagoas',
  discriminacao: 'Investment Calças navigating',
  municipioPrestacaoServico: 'protocol secured Casa',
  paisPrestacaoServico: 'Acre',
  codRegimeEspecialTributacao: 61663,
  codigoTributacaoMunicipio: 'withdrawal',
  itemListaServicoMunicipio: 'applications',
  cpfCnpjTomador: 'calculating coral Internal',
  inscricaoMunicipalTomador: 'throughput',
  indicadorCpfCnpjTomador: 2086,
  paisPrestador: 'quantifying',
  codCidadeTomadorIBGE: 'cultivate cultivate mesh',
  codCidadePrestadorIBGE: 'Espírito navigating',
  numeroEmpenho: 'generation Denar',
  idTipoAnexoSimplesNacional: 'programming mobile',
  idPgdasd2018Atividade: 'Solutions Cambridgeshire',
};

export const sampleWithFullData: INfse = {
  id: 77789,
  idNfse: 'capacitor',
  competencia: 'hack Account',
  dataEmissao: 'Bulgarian',
  ip: 'Refinado',
  optanteSimplesNacional: 'Integration end-to-end',
  outrasInformacoes: 'high-level Investment',
  idNfseSubstituida: 'bandwidth Borders',
  usuario: 'Marginal marrom',
  statusNfse: 'Helena USB Operations',
  naturezaOperacao: 89092,
  rps: 'quantifying Mesa connecting',
  inscricaoPrestador: 'rosa deliverables',
  tipoDocDigitado: 'experiences escarlate groupware',
  statusAceite: 18615,
  exclusaoLogica: 'withdrawal Legacy vermelho',
  ajustada: 'sensor Latvia Avenida',
  observacaoAjuste: 'protocol Lari Timor-Leste',
  aliquotaServico: 'Liaison neural',
  art: 'groupware quantifying Macio',
  baseCalculo: 'Plástico',
  codigoObra: 'quantifying panel Fresco',
  valorServico: 'human-resource Noruega',
  valorPis: 'mobile Computador Beleza',
  valorLiquidoNfse: 'Account',
  valorIssRetido: 'action-items Paradigm',
  valorIssOutroMunicipio: 'navigating',
  valorIss: 'Corporate impactful',
  valorIr: 'Esportes directional hard',
  valorInss: 'extend Technician Alameda',
  valorDescontoCondicionado: 'matrix Setentrionais Implemented',
  valorDescontoIncondicionado: 'Agent SCSI',
  valorDeducoes: 'Credit',
  valorCsll: 'withdrawal',
  valorCredito: 'neural Direct 1080p',
  valorCofins: 'IB Incrível',
  outrasRetencoes: 'application Licenciado',
  issRetido: 'Eletrônicos Planner',
  discriminacao: 'Salgadinhos',
  municipioPrestacaoServico: 'Congelado',
  paisPrestacaoServico: 'violeta',
  codRegimeEspecialTributacao: 87891,
  codigoTributacaoMunicipio: 'Luvas caramelo object-oriented',
  itemListaServicoMunicipio: 'withdrawal',
  cpfCnpjTomador: 'Industrial compressing',
  cpfCnpjPrestador: 'wireless Mesa Rústico',
  inscricaoMunicipalTomador: 'Turismo Síria',
  indicadorCpfCnpjTomador: 32473,
  indicadorCpfCnpjPrestador: 51196,
  paisTomador: 'Cook',
  paisPrestador: 'bus redundant Grass-roots',
  tipoTomador: 14651,
  codCidadeTomadorIBGE: 'vertical esmeralda',
  codCidadePrestadorIBGE: 'virtual Angola incubate',
  tipoPrestador: 13074,
  numeroEmpenho: 'reintermediate Macio',
  tipoTributacaoPrestExterno: 'Ameliorated marrom innovate',
  cepPrestador: 'deposit',
  cepTomador: 'navigating Paraíba productize',
  idTipoAnexoSimplesNacional: 'Regional Multi-channelled mobile',
  idBloqueioNfse: 99078,
  idPgdasd2018Atividade: 'Dollar Corporate',
};

export const sampleWithNewData: NewNfse = {
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
