import { IInscricaoCPBS } from 'app/entities/inscricao-cpbs/inscricao-cpbs.model';

export interface INfse {
  id: number;
  idNfse?: string | null;
  competencia?: string | null;
  dataEmissao?: string | null;
  ip?: string | null;
  optanteSimplesNacional?: string | null;
  outrasInformacoes?: string | null;
  idNfseSubstituida?: string | null;
  usuario?: string | null;
  statusNfse?: string | null;
  naturezaOperacao?: number | null;
  rps?: string | null;
  inscricaoPrestador?: string | null;
  tipoDocDigitado?: string | null;
  statusAceite?: number | null;
  exclusaoLogica?: string | null;
  ajustada?: string | null;
  observacaoAjuste?: string | null;
  aliquotaServico?: string | null;
  art?: string | null;
  baseCalculo?: string | null;
  codigoObra?: string | null;
  valorServico?: string | null;
  valorPis?: string | null;
  valorLiquidoNfse?: string | null;
  valorIssRetido?: string | null;
  valorIssOutroMunicipio?: string | null;
  valorIss?: string | null;
  valorIr?: string | null;
  valorInss?: string | null;
  valorDescontoCondicionado?: string | null;
  valorDescontoIncondicionado?: string | null;
  valorDeducoes?: string | null;
  valorCsll?: string | null;
  valorCredito?: string | null;
  valorCofins?: string | null;
  outrasRetencoes?: string | null;
  issRetido?: string | null;
  discriminacao?: string | null;
  municipioPrestacaoServico?: string | null;
  paisPrestacaoServico?: string | null;
  codRegimeEspecialTributacao?: number | null;
  codigoTributacaoMunicipio?: string | null;
  itemListaServicoMunicipio?: string | null;
  cpfCnpjTomador?: string | null;
  cpfCnpjPrestador?: string | null;
  inscricaoMunicipalTomador?: string | null;
  indicadorCpfCnpjTomador?: number | null;
  indicadorCpfCnpjPrestador?: number | null;
  paisTomador?: string | null;
  paisPrestador?: string | null;
  tipoTomador?: number | null;
  codCidadeTomadorIBGE?: string | null;
  codCidadePrestadorIBGE?: string | null;
  tipoPrestador?: number | null;
  numeroEmpenho?: string | null;
  tipoTributacaoPrestExterno?: string | null;
  cepPrestador?: string | null;
  cepTomador?: string | null;
  idTipoAnexoSimplesNacional?: string | null;
  idBloqueioNfse?: number | null;
  idPgdasd2018Atividade?: string | null;
  inscricaoCpbs?: Pick<IInscricaoCPBS, 'id' | 'inscricao'> | null;
}

export type NewNfse = Omit<INfse, 'id'> & { id: null };
